version: '3.8'

services:
  app:
    build:
      context: .
    container_name: laravel-inertia
    restart: unless-stopped
    volumes:
      - .:/var/www
    expose:
      - '9000'

  web:
    image: nginx:alpine
    container_name: nginx-laravel
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
